# Generated by Django 5.2.7 on 2025-11-11 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='users.user'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.user'),
        ),
        migrations.AlterField(
            model_name='ordershipping',
            name='estimated_delivery',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='ordershipping',
            table='order_shipping',
        ),
    ]
