# Generated by Django 5.2.7 on 2025-11-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='dimension',
            new_name='dimensions',
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(default='NGN', max_length=3),
        ),
    ]
